name: Benchmarks Tests
on: [push, pull_request]
jobs:
  Run-Unit-Tests:
    name: Benchmark Unit Tests
    runs-on: windows-latest
    steps:
      - run: echo "Checking out benchmarks code"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Grab Dependencies and Create Conda Environment
        run: |
          C:\Miniconda\condabin\conda.bat env create -f benchmarks-win.yml
      - name: Activate Conda Environment and Run CMake
      - run: |
          C:\Miniconda\condabin\conda.bat activate benchmarks-dev
          cmake --preset=win -B build -DCXXTEST_ADD_PERFORMANCE=ON
      - name: Build Benchmarks and Run Unit Tests
      - run: |
          build\command-prompt.bat
          msbuild build/benchmarks.sln /p:Configuration=Release
          ctest -C Release -V --test-dir ./build --output-on-failure --stop-on-failure
      - run: echo "Job status ${{ job.status }}."